[package]
name = "processbeacon"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.0"   # Adjust based on your environment
hostname = "0.3.1"
chrono = "0.4.0"
windows-service = "0.5.0"